#!/usr/bin/env python3
"""Shared target and model constants for runtime resolver scorer training."""

from __future__ import annotations

TARGET_CANDIDATE_FAILURE_OR_HIGH_GAP = "candidate_failure_or_high_gap"
TARGET_NORMALIZED_REGRET = "normalized_regret"
TARGET_ORACLE_REGRET = "oracle_regret"
TARGET_DOWNSTREAM_WEIGHTED_ALIGNMENT_COST = "downstream_weighted_alignment_cost"
# Backward-compatible constant name used by trainer/evaluator call sites.
TARGET_SELECTION_COST = TARGET_DOWNSTREAM_WEIGHTED_ALIGNMENT_COST

CLASSIFIER_TARGETS: tuple[str, ...] = (TARGET_CANDIDATE_FAILURE_OR_HIGH_GAP,)
REGRESSION_TARGETS: tuple[str, ...] = (
    TARGET_NORMALIZED_REGRET,
    TARGET_ORACLE_REGRET,
    TARGET_SELECTION_COST,
)
SCORER_TARGETS: tuple[str, ...] = (*CLASSIFIER_TARGETS, *REGRESSION_TARGETS)

MODEL_TYPE_LOGISTIC_REGRESSION = "logistic_regression"
MODEL_TYPE_LINEAR_REGRESSION = "linear_regression"
MODEL_TYPE_LIGHTGBM_LAMBDARANK = "lightgbm_lambdarank"
SCORE_SEMANTICS_PREDICTED_RISK = "predicted_risk"
SCORE_SEMANTICS_PREDICTED_COST = "predicted_cost"

DEFAULT_NME_FAILURE_THRESHOLD: float = 0.08
DEFAULT_LARGE_REGRET_THRESHOLD: float = 0.01
DEFAULT_REGRET_NORMALIZER: float = 0.03
DEFAULT_FAILURE_COST_PENALTY: float = 2.0
DEFAULT_COLLAPSE_COST_PENALTY: float = 0.5
DEFAULT_LARGE_COST_THRESHOLD: float = 1.0


__all__ = [
    "CLASSIFIER_TARGETS",
    "DEFAULT_COLLAPSE_COST_PENALTY",
    "DEFAULT_FAILURE_COST_PENALTY",
    "DEFAULT_LARGE_COST_THRESHOLD",
    "DEFAULT_LARGE_REGRET_THRESHOLD",
    "DEFAULT_NME_FAILURE_THRESHOLD",
    "DEFAULT_REGRET_NORMALIZER",
    "MODEL_TYPE_LINEAR_REGRESSION",
    "MODEL_TYPE_LIGHTGBM_LAMBDARANK",
    "MODEL_TYPE_LOGISTIC_REGRESSION",
    "REGRESSION_TARGETS",
    "SCORE_SEMANTICS_PREDICTED_COST",
    "SCORE_SEMANTICS_PREDICTED_RISK",
    "SCORER_TARGETS",
    "TARGET_CANDIDATE_FAILURE_OR_HIGH_GAP",
    "TARGET_NORMALIZED_REGRET",
    "TARGET_ORACLE_REGRET",
    "TARGET_DOWNSTREAM_WEIGHTED_ALIGNMENT_COST",
    "TARGET_SELECTION_COST",
]
